import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import InputSearch from '@/components/InputSearch'
import ErrorButton from '@/components/ErrorButton'
import { GetServerSideProps, GetServerSidePropsContext, InferGetServerSidePropsType } from 'next'
import { json } from 'stream/consumers'
import { Item } from '@/types/types'
import ListItems from '@/components/ListItems'

type State = {
    error?: string;
    isLoaded?: boolean;
    items: Item[];
  };
 
export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  const result = await fetch('https://rickandmortyapi.com/api/character/?page=1')
  return { 
    props:  {
    result: await result.json()
  }}
}

export default function Home(props: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Rick & Morty</title>
        <link rel="icon" 
        type="image/svg+xml"
        href="https://www.svgrepo.com/show/1321/planet.svg" />
      </Head>
      <main className={styles.main}>
        {/* <div>{repo.stargazers_count}</div> */}
      <div>
            <ErrorButton />
          </div>
        <div className={styles.center}>
          <div>
          <InputSearch/>
        </div>
        
        </div>

        <div className={styles.grid}>
          <ListItems items={props.result.results}/>
        </div>
      </main>
    </>
  )
}
