import Head from 'next/head';

const Layout = () => {
  return (
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>Rick & Morty</title>
      <link rel="icon" type="image/svg+xml" href="https://www.svgrepo.com/show/1321/planet.svg" />
    </Head>
  );
};
export default Layout;
